#!/bin/bash

# Extract required fields using jq
jq -r '[.name, (.types[0].type.name), .weight, .height] | @csv' data.json | \
# Process with awk to format the initial output
awk -F',' '{ printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", \
toupper(substr($1,1,1))substr($1,2), \
$2, \
$3/10, \
$4/10 }' | \
# Use sed to ensure proper capitalization of the type name
sed 's/\(is of type \)\([a-z]\)/\1\u\2/g'